### ISSUE TITLE
Script to train SVHN dataset

### ISSUE THREAD

**Issue by dlmacedo** [szagoruyko/wide-residual-networks#13]
Dear friend,

Are we supposed to use the script named "train_cifar.sh" also to train on SVHN?

If yes, I think it is a good idea to change the name of the file.

David

**Comment by szagoruyko** [comment]
done via https://github.com/szagoruyko/wide-residual-networks/commit/5ed3b7293d0b76a2fb8cb80bb6436ac477c1c3f4
