### ISSUE TITLE
Why 6n + 4?

### ISSUE THREAD

**Issue by shawnLeeZX** [szagoruyko/wide-residual-networks#18]
Hi,

I am trying to reproduce the result using tensorflow, and found that the number of conv layer is 6n + 4 instead of 6n + 2. Why is this the case? I did not find it in the paper.

Thanks a lot!

**Comment by szagoruyko** [comment]
did you count downsampling convolutions? https://github.com/szagoruyko/wide-residual-networks/blob/master/models/wide-resnet.lua#L67

**Comment by shawnLeeZX** [comment]
Oh, that should be the reason. Thanks!
