### ISSUE TITLE
projection shortcut issues

### ISSUE THREAD

**Issue by youngwanLEE** [szagoruyko/wide-residual-networks#19]
Hi, Szagoruyko.

Firstly, I was inspired by your excellent paper. 

I have a question about your implementation.

Identity mapping paper stated when increasing dimensions, project shortcuts are also with pre-activation. 

So I think Project shortcuts also consist of BN-ReLU-Conv layers. 

I want to know your opinion about this issue.

Thanks

**Comment by szagoruyko** [comment]
sorry, about what issue? our model follows https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua

**Comment by youngwanLEE** [comment]
thank you :)
