### ISSUE TITLE
optnet issue

### ISSUE THREAD

**Issue by youngwanLEE** [szagoruyko/wide-residual-networks#20]
Hi,

I could run train.lua normally. However, After rebooting my PC, when I tried to run train.lua, I faced this problem.

> /home/youngwan/torch/install/bin/luajit: /home/youngwan/torch/install/share/lua/5.1/trepl/init.lua:384: module 'optnet' not found:No LuaRocks module found for optnet
>   no field package.preload['optnet']
>   no file '/home/youngwan/.luarocks/share/lua/5.1/optnet.lua'
>   no file '/home/youngwan/.luarocks/share/lua/5.1/optnet/init.lua'
>   no file '/home/youngwan/torch/install/share/lua/5.1/optnet.lua'
>   no file '/home/youngwan/torch/install/share/lua/5.1/optnet/init.lua'
>   no file './optnet.lua'
>   no file '/home/youngwan/torch/install/share/luajit-2.1.0-beta1/optnet.lua'
>   no file '/usr/local/share/lua/5.1/optnet.lua'
>   no file '/usr/local/share/lua/5.1/optnet/init.lua'
>   no file '/home/youngwan/.luarocks/lib/lua/5.1/optnet.so'
>   no file '/home/youngwan/torch/install/lib/lua/5.1/optnet.so'
>   no file '/home/youngwan/torch/install/lib/optnet.so'
>   no file './optnet.so'
>   no file '/usr/local/lib/lua/5.1/optnet.so'
>   no file '/usr/local/lib/lua/5.1/loadall.so'
> stack traceback:
>   [C]: in function 'error'
>   /home/youngwan/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
>   train.lua:14: in main chunk
>   [C]: in function 'dofile'
>   ...gwan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>   [C]: at 0x004065d0

 checking opnet.so files in /torch/install/lib... , There are no any optnet libs. 
so, I tried to 'luarocks install optnet ' again. 

> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Found Torch7 in /usr
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/luarocks_optnet-scm-1-7703/optimize-net/build
> cd build && make install
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/utils.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/example.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/models.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/init.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/graphgen.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/env.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/countUsedMemory.lua
> -- Installing: /usr/lib/luarocks/rocks/optnet/scm-1/lua/optnet/tests.lua
> Updating manifest for /usr/lib/luarocks/rocks

Terminal display like this. But the problem occur again.

**Comment by youngwanLEE** [comment]
Sorry, I solved it.

**Comment by dingjiansw101** [comment]
Hi, I also meet the problem. How do you solve it?

**Comment by petergerten** [comment]
@youngwanLEE It would be great if you actually share how you solved it. People like me find this googling and a "I solved it." is a bit frustrating to find ;-)

**Comment by deepconsc** [comment]
`luarocks install optnet` 🤝
