### ISSUE TITLE
test accuracy issue

### ISSUE THREAD

**Issue by youngwanLEE** [szagoruyko/wide-residual-networks#21]
Hi, I have two questions.

1)
When you test, is the accuracy on batch_size : 128 ? 

If so, the accuracy on your paper is based on using batch size 128 or all test images 10k ? 

Because I'm unfamiliar with torch, I can't figure out all your code yet.

2) 
What the difference between the master branch and the multigpu branch?

Thanks

**Comment by szagoruyko** [comment]
Hi,
1) the accuracy is computed on all test images using minibatches of size 128 + the last smaller minibatch, see here https://github.com/szagoruyko/wide-residual-networks/blob/master/train.lua#L141
2) master branch has multiGPU support already, forgot to remove the old branch

**Comment by youngwanLEE** [comment]
@szagoruyko  thanks :)
