### ISSUE TITLE
FP16 and FP32

### ISSUE THREAD

**Issue by shuzi** [szagoruyko/wide-residual-networks#30]
Hi ,  would you please point me to the part of code that can switch between FP32 mode and FP16 mode ?

**Comment by szagoruyko** [comment]
@shuzi see https://github.com/szagoruyko/wide-residual-networks/tree/fp16 branch and set `data_type=torch.CudaHalfTensor th train.lua` to train in float16

**Comment by shuzi** [comment]
@szagoruyko 

just curious,  when you use FP16 on P100 card,  the optimization still converges?

**Comment by szagoruyko** [comment]
@shuzi I don't have a P100 card.

**Comment by szagoruyko** [comment]
Models in pytorch hub were trained in FP16 https://pytorch.org/hub/pytorch_vision_wide_resnet/
