### ISSUE TITLE
What is exactly factor k?

### ISSUE THREAD

**Issue by saix47** [szagoruyko/wide-residual-networks#33]
Sorry for stupid question, but I understand that k multiplies the number of feature MAPs in cnn layers. So in the first layer, you use 16 feature planes, the second will be 16*k feature planes and so on. But what is the difference to original deep residual net? I read original one https://arxiv.org/pdf/1512.03385.pdf, and see that authors also increase number of feature planes (Figure 3). Please point out for me the difference?

**Comment by szagoruyko** [comment]
@saix47 this line should explain it https://github.com/szagoruyko/wide-residual-networks/blob/master/models/wide-resnet.lua#L93
original resnet increases #planes only at each new group of blocks, wide resnet has k times more #planes in **each** 3x3 convolution

**Comment by saix47** [comment]
Oh, thanks. I got it.
