### ISSUE TITLE
torchvision.cvtransforms question

### ISSUE THREAD

**Issue by bkj** [szagoruyko/wide-residual-networks#38]
Where might I be able to find the proper version of `torchvision` that includes `cvtransforms`?  Doesn't seem to be in the current conda or Github versions.

Thanks
Ben

**Comment by szagoruyko** [comment]
it exists in https://github.com/szagoruyko/vision/tree/opencv fork, but I now copy-paste the file to every project for simplicity.

added via https://github.com/szagoruyko/wide-residual-networks/commit/375d77ae0752390bd3b3a2c4a4a3c295fcc9a363#diff-048e28f029d36925930e391b48889c39
