### ISSUE TITLE
input size

### ISSUE THREAD

**Issue by ghost** [szagoruyko/wide-residual-networks#4]
I have such a problem and would like to get any advices: 

Here is the model, which I got by seting depth = 10.
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> output](1): cudnn.SpatialConvolution(3 -> 16, 3x3, 1,1, 1,1)
  (2): nn.Sequential {
    [input -> (1) -> output](1): nn.Sequential {
      [input -> (1) -> (2) -> output](1): nn.ConcatTable {
        input
          |`-> (1): nn.Sequential {
          |      [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> output]
          |      (1): nn.SpatialBatchNormalization
          |      (2): cudnn.ReLU
          |      (3): cudnn.SpatialConvolution(16 -> 16, 3x3, 1,1, 1,1)
          |      (4): nn.SpatialBatchNormalization
          |      (5): cudnn.ReLU
          |      (6): cudnn.SpatialConvolution(16 -> 16, 3x3, 1,1, 1,1)
          |    }
          |`-> (2): nn.Identity
           ... -> output
      }
      (2): nn.CAddTable
    }
  }
  (3): nn.Sequential {
    [input -> (1) -> output](1): nn.Sequential {
      [input -> (1) -> (2) -> (3) -> (4) -> output](1): nn.SpatialBatchNormalization
      (2): cudnn.ReLU
      (3): nn.ConcatTable {
        input
          |`-> (1): nn.Sequential {
          |      [input -> (1) -> (2) -> (3) -> (4) -> output]
          |      (1): cudnn.SpatialConvolution(16 -> 32, 3x3, 2,2, 1,1)
          |      (2): nn.SpatialBatchNormalization
          |      (3): cudnn.ReLU
          |      (4): cudnn.SpatialConvolution(32 -> 32, 3x3, 1,1, 1,1)
          |    }
          |`-> (2): cudnn.SpatialConvolution(16 -> 32, 1x1, 2,2)
           ... -> output
      }
      (4): nn.CAddTable
    }
  }
  (4): nn.Sequential {
    [input -> (1) -> output](1): nn.Sequential {
      [input -> (1) -> (2) -> (3) -> (4) -> output](1): nn.SpatialBatchNormalization
      (2): cudnn.ReLU
      (3): nn.ConcatTable {
        input
          |`-> (1): nn.Sequential {
          |      [input -> (1) -> (2) -> (3) -> (4) -> output]
          |      (1): cudnn.SpatialConvolution(32 -> 64, 3x3, 2,2, 1,1)
          |      (2): nn.SpatialBatchNormalization
          |      (3): cudnn.ReLU
          |      (4): cudnn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
          |    }
          |`-> (2): cudnn.SpatialConvolution(32 -> 64, 1x1, 2,2)
           ... -> output
      }
      (4): nn.CAddTable
    }
  }
  (5): nn.SpatialBatchNormalization
  (6): cudnn.ReLU
  (7): cudnn.SpatialAveragePooling(8x8, 1,1)
  (8): nn.View(64)
  (9): nn.Linear(64 -> 1000)
}

And Network has 9   convolutions.

Then I ran the following line:

```
  local output = model:forward(input):float()
```

The input is this size:
input=  
   1
   3
 224
 224
[torch.LongStorage of size 4]

Now I got such ouput:
output= 
 2401
 1000
[torch.LongStorage of size 2]

I thought it should be 1 \* 1000 since the input is just one image, but why 2401 \* 1000, any help please?

**Comment by szagoruyko** [comment]
looks like you're trying to use CIFAR network on ImageNet size images

**Comment by ghost** [comment]
Thanks, noticed that and "fixed".
