### ISSUE TITLE
Wide Residual Networks on imagenet

### ISSUE THREAD

**Issue by antspy** [szagoruyko/wide-residual-networks#46]
Hi, 

Is there a version that works on imagenet? I tried using the pytorch model definition, but I think it only works if input images are 32x32. Thank you!

**Comment by szagoruyko** [comment]
@antspy yes I have the pytorch code to train WRN on ImageNet, will try to push it today or tomorrow

**Comment by antspy** [comment]
@szagoruyko  Great! Thank you very much :-)

**Comment by jennyzu** [comment]
@szagoruyko  Where can I find the WRN train on imagenet? will like to especially get the hyper-parameters. Thanks!

**Comment by guanfuchen** [comment]
@szagoruyko Where is the code for imagenet implementing using PyTorch? I find the PyTorch version is for 32x32

**Comment by xwuShirley** [comment]
@szagoruyko   The code for imagenet implementing using PyTorch has been released?

**Comment by szagoruyko** [comment]
This code should work: https://github.com/pytorch/vision/blob/c187c2b12d86c3909e59a40dbe49555d85b98703/references/classification/train.py
just need to set `--model wide_resnet50_2` or `--model wide_resnet101_2`
