### ISSUE TITLE
"resume" option in pytorch code

### ISSUE THREAD

**Issue by Itsukara** [szagoruyko/wide-residual-networks#50]
Thank your for your great code!

I tried your pytorch code by following command. It is only 10 epochs because my PC is slow.
```python main.py --save ./logs/resnet_02c --depth 10 --width 10 --epochs 10```

After that, I tried "resume" option by following command.
```python main.py --save ./logs/resnet_02c --depth 10 --width 10 --epochs 12 --resume logs/resnet_02c/model.pt7```

Unfortunately, it became following error.
Is "resume" option working in your environment?

```
...
Total number of parameters: 7435354
  0%|                                                                  | 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 216, in <module>
    main()
  File "main.py", line 212, in main
    engine.train(h, train_loader, opt.epochs, optimizer)
  File "/home/itsukara/anaconda2/envs/pytorch3/lib/python3.5/site-packages/torchnet/engine/engine.py", line 39, in train
    state['optimizer'].step(closure)
  File "/home/itsukara/anaconda2/envs/pytorch3/lib/python3.5/site-packages/torch/optim/sgd.py", line 94, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: invalid argument 3: sizes do not match at /opt/conda/conda-bld/pytorch_1513366702650/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:271
```

**Comment by szagoruyko** [comment]
Thank you very much! I've just tried your commands, resume works for me. What is the version of pytorch you're using?

**Comment by Itsukara** [comment]
Thank you for trying in your environment. It looks like my environment is bad. My environment is following. I installed pytorch in conda environment by ```conda install pytorch ```. What environment do you use?
```
python                    3.5.1                         5  
pytorch                   0.3.0           py35cuda8.0cudnn7.0_0  

```

**Comment by Itsukara** [comment]
I tried and found following facts. So, (2) is the best environment.

```
(1) python 2.7 + pytorch0.1.12 : resume is OK (2 times SLOWER than (2))
(2) python 2.7 + pytorch0.3.0  : resume is OK
(3) python 3.5 + pytorch0.1.12 : resume is NG (2 times SLOWER than (4))
(4) python 3.5 + pytorch0.3.0  : resume is NG
```
BTW, when install opencv by ```conda install -c menpo opencv3```, pytorch is downgraded to pytorch0.1.12.
But, when install opencv by ```conda install opencv```, pytorch is not downgraded.
So, you had better to install opencv by this command.

Additionally, I think everybody would appreciate you if you could change your code to work "resume option" in python 3.5 too.

**Comment by szagoruyko** [comment]
thanks, I didn't know that. can you try python3.6 ? that's what I am on

**Comment by Itsukara** [comment]
I found that resume is OK in python 3.6 + pytorch0.3.0 .
Additionally,  command ```conda install -c menpo opencv3``` will not downgraded pytorch.
So, your environment is the best!

```
(5) python 3.6 + pytorch0.3.0  : resume is OK
```
Thank you for teaching me your environment.
I'd like to use python 3.6 rather than python 3.5 hereafter.

**Comment by szagoruyko** [comment]
@Itsukara I removed dependency on opencv, should be easier to use the code now.

**Comment by Itsukara** [comment]
@szagoruyko Thank you for removing dependency. It will be useful for everyone.
