### ISSUE TITLE
Why the depth is 6n+4, rather than 6n+2?

### ISSUE THREAD

**Issue by cheerss** [szagoruyko/wide-residual-networks#63]
Thanks for your great work!

I wonder why the depth of network is 6n+4 for WRN for cifar. I could understand that 6n means there are n blocks and 6 layers per block. Besides, there is an extra convolutional layer before all blocks and a linear layer after all blocks. So I think the depth should be 6n+2, which is same as original Resnet. 

Hope for your reply!

**Comment by 18445864529** [comment]
https://www.zhihu.com/question/403515516

**Comment by cheerss** [comment]
@18445864529  Got it. Thanks!
